[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# STM32WBA65RI is based on Cortex-M33
runner = "probe-rs run --chip STM32WBA65RI --speed 4000"

rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
# STM32WBA65RI uses Cortex-M33
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trace"
