[package]
name = "lorawan"
version = "0.5.0"
edition = "2018"
authors = ["Ivaylo Petrov <ivajloip@gmail.com>"]
description = "Crate lorawan provides structures and tools for reading and writing LoRaWAN messages from and to a slice of bytes."
repository = "https://github.com/ivajloip/rust-lorawan"
license = "MIT"
keywords = ["lorawan", "iot", "lpwan", "parser", "lightweight"]

[dependencies]
aes = { version = "0.3.2", optional = true }
cmac = { version = "0.2.0", optional = true }
generic-array = "0.12.0"
heapless = "0.5.4"

[dev-dependencies]
criterion = "0.3"
trallocator = { path = "./trallocator" }

[[bench]]
name = "lorawan"
harness = false

[profile.release]
debug = true

[features]
default = ["full"]

full = ["with-to-string", "with-downlink", "default-crypto"]

default-crypto = ["aes", "cmac"]

with-to-string = []

with-downlink = []
