[package]
name = "lora-phy"
version = "3.0.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/embassy-rs/lora-phy"
categories = ["embedded", "no-std", "asynchronous"]
keywords = ["lora", "radio", "embedded-hal-async", "iot", "semtech"]
description = "A LoRa physical layer implementation enabling utilization of a range of MCU/LoRa board combinations within embedded frameworks supporting embedded-hal-async."

[dependencies]
defmt = { version = "0.3" }
lora-modulation = { version = ">=0.1.2" }
num-traits = { version = "0.2", default-features = false }

embedded-hal-async = { version = "=1.0.0-rc.2"}
