[package]
name = "lorawan-device"
version = "0.2.0"
authors = ["Louis Thiery <louis@helium.com>"]
edition = "2018"
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
license = "Apache 2.0"
readme = "README.md"
description = "A Rust LoRaWAN device stack implementation"

[dependencies]
lorawan-encoding = { path = "../encoding", default-features = false }
heapless = "0.5.4"
as-slice = "*"
generic-array = "0.14.2"
