[package]
name = "lorawan-device"
version = "0.10.0"
authors = ["Louis Thiery <louis@helium.com>", "Ulf Lilleengen <lulf@redhat.com>"]
edition = "2018"
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
license = "Apache-2.0"
readme = "README.md"
description = "A Rust LoRaWAN device stack implementation"

[dependencies]
lorawan = { version = "0.7.3", path = "../encoding", default-features = false }
heapless = "0.7.5"
as-slice = "0.2"
generic-array = "0.14.2"
defmt = { version = "0.3.0", optional = true }
futures = { version = "0.3.17", default-features = false, optional = true }
rand_core = { version = "0.6.2", default-features = false }
serde = { version = "1.0.145", default-features = false, features = ["derive"], optional = true}
lora-phy = { version = "1.1.0", optional = true }

[features]
defmt = ["dep:defmt", "lorawan/defmt"]
default = []
async = ["futures"]
serde = ["dep:serde"]
external-lora-phy = ["lora-phy"]
async-rng = ["external-lora-phy", "async" ]
